# Generated by Django 5.0.6 on 2024-05-21 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreciudad', models.CharField(max_length=50, verbose_name='Nombre ciudad')),
                ('descripcionciudad', models.CharField(max_length=100, verbose_name='Descripcion ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='tipodocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombretipodocumento', models.CharField(max_length=50, verbose_name='Nombre tipo documento')),
                ('descripciontipodocumento', models.CharField(max_length=100, verbose_name='Descripcion tipo documento')),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('documento', models.CharField(max_length=50, verbose_name='documento')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('fechanacimiento', models.DateField(verbose_name='Fecha nacimiento')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('usuario', models.CharField(max_length=50, verbose_name='Usuario')),
                ('clave', models.CharField(max_length=50, verbose_name='Clave')),
                ('lugarresidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.ciudad')),
                ('idtipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.tipodocumento')),
            ],
        ),
    ]
